### ISSUE TITLE
[documentation] Lien mort sécurité dépendances back

### ISSUE THREAD

**Issue by yannbertrand** [france-connect/sources#1]
Bonjour et merci pour l'ouverture en Open Source.

Sur https://github.com/france-connect/sources/tree/main/back est référencé un fichier `_doc/sécurité-dépendances.md` qui n'existe pas pour le moment. Est-il prévu de le rendre public ?

De même dans https://github.com/france-connect/sources/tree/main/back/_doc#s%C3%A9curit%C3%A9-des-d%C3%A9pendances, un lien vers un différent document est mort.

**Comment by sherman-dinum** [comment]
Bonjour,

Effectivement ce fichier a été retiré lors de la mise en open-source car il est avant tout à destination des équipes de dev internes. Il contient des informations que notre équipe SSI n'a pas souhaité divulguer pour le moment. Cela pourra être amené à changer dans le futur (c'est même en fait l'objectif :smiley:).

Pour information nous publierons le code à chacune de nos fins d'itérations, soit environ toutes les deux semaines.

Merci de votre intérêt et n'hésitez pas à nous faire remonter si vous vous avez d'autres questions ou des remarques / corrections :+1:.

**Comment by yannbertrand** [comment]
Merci pour votre retour 👍

Vous pouvez clôturer l'issue si vous le souhaitez 😄
