### ISSUE TITLE
nonce should be optional

### ISSUE THREAD

**Issue by mehdisfdc** [france-connect/sources#4]
The [OpenID Connect Core specification](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) defines the `nonce` parameter as OPTIONAL.

It should not be required by FranceConnect.

**Comment by sherman-dinum** [comment]
Dear [mehdisfdc](https://github.com/mehdisfdc),

Sorry for the latency, you are absolutly right about the specification. Depsite that, we are required as per our control authority (ANSSI) to set it as mandatory. The state parameter has the same treatment.

**Comment by mehdisfdc** [comment]
Ok, thank you for the feedback @sherman-dinum!
